package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name="Evento"
    ,catalog="eventos"
)
public class Evento  implements java.io.Serializable {


     private Integer idEvento;
     private String nomeEvento;
     private int estado;
     private String nomeCliente;
     private String contactoCliente;
     private String emailCliente;
     private String descricao;
     private Date dataInicio;
     private Date dataFim;
     private Date horaInicio;
     private Date horaFim;
     private int apoioCamara;
     private int idTipoEvento;
     private int visivel;

    public Evento() {
    }

    public Evento(String nomeEvento, int estado, String nomeCliente, String contactoCliente, String emailCliente, String descricao, Date dataInicio, Date dataFim, Date horaInicio, Date horaFim, int apoioCamara, int idTipoEvento, int visivel) {
       this.nomeEvento = nomeEvento;
       this.estado = estado;
       this.nomeCliente = nomeCliente;
       this.contactoCliente = contactoCliente;
       this.emailCliente = emailCliente;
       this.descricao = descricao;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
       this.horaInicio = horaInicio;
       this.horaFim = horaFim;
       this.apoioCamara = apoioCamara;
       this.idTipoEvento = idTipoEvento;
       this.visivel = visivel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_evento", unique=true, nullable=false)
    public Integer getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(Integer idEvento) {
        this.idEvento = idEvento;
    }

    
    @Column(name="nomeEvento", nullable=false, length=45)
    public String getNomeEvento() {
        return this.nomeEvento;
    }
    
    public void setNomeEvento(String nomeEvento) {
        this.nomeEvento = nomeEvento;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

    
    @Column(name="nomeCliente", nullable=false, length=45)
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }

    
    @Column(name="contactoCliente", nullable=false, length=45)
    public String getContactoCliente() {
        return this.contactoCliente;
    }
    
    public void setContactoCliente(String contactoCliente) {
        this.contactoCliente = contactoCliente;
    }

    
    @Column(name="emailCliente", nullable=false, length=45)
    public String getEmailCliente() {
        return this.emailCliente;
    }
    
    public void setEmailCliente(String emailCliente) {
        this.emailCliente = emailCliente;
    }

    
    @Column(name="descricao", nullable=false, length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataInicio", nullable=false, length=10)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataFim", nullable=false, length=10)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="horaInicio", nullable=false, length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="horaFim", nullable=false, length=8)
    public Date getHoraFim() {
        return this.horaFim;
    }
    
    public void setHoraFim(Date horaFim) {
        this.horaFim = horaFim;
    }

    
    @Column(name="apoioCamara", nullable=false)
    public int getApoioCamara() {
        return this.apoioCamara;
    }
    
    public void setApoioCamara(int apoioCamara) {
        this.apoioCamara = apoioCamara;
    }

    
    @Column(name="id_tipoEvento", nullable=false)
    public int getIdTipoEvento() {
        return this.idTipoEvento;
    }
    
    public void setIdTipoEvento(int idTipoEvento) {
        this.idTipoEvento = idTipoEvento;
    }

    
    @Column(name="visivel", nullable=false)
    public int getVisivel() {
        return this.visivel;
    }
    
    public void setVisivel(int visivel) {
        this.visivel = visivel;
    }




}


