package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name="Feedback"
    ,catalog="eventos"
)
public class Feedback  implements java.io.Serializable {


     private Integer idFeedback;
     private int nota;
     private String observacao;
     private int idEvento;

    public Feedback() {
    }

    public Feedback(int nota, String observacao, int idEvento) {
       this.nota = nota;
       this.observacao = observacao;
       this.idEvento = idEvento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_feedback", unique=true, nullable=false)
    public Integer getIdFeedback() {
        return this.idFeedback;
    }
    
    public void setIdFeedback(Integer idFeedback) {
        this.idFeedback = idFeedback;
    }

    
    @Column(name="nota", nullable=false)
    public int getNota() {
        return this.nota;
    }
    
    public void setNota(int nota) {
        this.nota = nota;
    }

    
    @Column(name="observacao", nullable=false, length=45)
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    
    @Column(name="id_evento", nullable=false)
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }




}


