package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Local generated by hbm2java
 */
@Entity
@Table(name="Local"
    ,catalog="eventos"
    , uniqueConstraints = @UniqueConstraint(columnNames="nome") 
)
public class Local  implements java.io.Serializable {


     private Integer idLocal;
     private String nome;
     private String morada;
     private String codigoPostal;

    public Local() {
    }

    public Local(String nome, String morada, String codigoPostal) {
       this.nome = nome;
       this.morada = morada;
       this.codigoPostal = codigoPostal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_local", unique=true, nullable=false)
    public Integer getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(Integer idLocal) {
        this.idLocal = idLocal;
    }

    
    @Column(name="nome", unique=true, nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="morada", nullable=false, length=100)
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }

    
    @Column(name="codigoPostal", nullable=false, length=10)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }




}


