package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LocalEvento generated by hbm2java
 */
@Entity
@Table(name="LocalEvento"
    ,catalog="eventos"
)
public class LocalEvento  implements java.io.Serializable {


     private LocalEventoId id;

    public LocalEvento() {
    }

    public LocalEvento(LocalEventoId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEvento", column=@Column(name="id_evento", nullable=false) ), 
        @AttributeOverride(name="idLocal", column=@Column(name="id_local", nullable=false) ) } )
    public LocalEventoId getId() {
        return this.id;
    }
    
    public void setId(LocalEventoId id) {
        this.id = id;
    }




}


