package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocalEventoId generated by hbm2java
 */
@Embeddable
public class LocalEventoId  implements java.io.Serializable {


     private int idEvento;
     private int idLocal;

    public LocalEventoId() {
    }

    public LocalEventoId(int idEvento, int idLocal) {
       this.idEvento = idEvento;
       this.idLocal = idLocal;
    }
   


    @Column(name="id_evento", nullable=false)
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }


    @Column(name="id_local", nullable=false)
    public int getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(int idLocal) {
        this.idLocal = idLocal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocalEventoId) ) return false;
		 LocalEventoId castOther = ( LocalEventoId ) other; 
         
		 return (this.getIdEvento()==castOther.getIdEvento())
 && (this.getIdLocal()==castOther.getIdLocal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEvento();
         result = 37 * result + this.getIdLocal();
         return result;
   }   


}


