package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MaterialEvento generated by hbm2java
 */
@Entity
@Table(name="MaterialEvento"
    ,catalog="eventos"
)
public class MaterialEvento  implements java.io.Serializable {


     private MaterialEventoId id;
     private int quantidadeUsadaRecurso;
     private int estado;

    public MaterialEvento() {
    }

    public MaterialEvento(MaterialEventoId id, int quantidadeUsadaRecurso, int estado) {
       this.id = id;
       this.quantidadeUsadaRecurso = quantidadeUsadaRecurso;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEvento", column=@Column(name="id_evento", nullable=false) ), 
        @AttributeOverride(name="idRecurso", column=@Column(name="id_recurso", nullable=false) ) } )
    public MaterialEventoId getId() {
        return this.id;
    }
    
    public void setId(MaterialEventoId id) {
        this.id = id;
    }

    
    @Column(name="quantidadeUsadaRecurso", nullable=false)
    public int getQuantidadeUsadaRecurso() {
        return this.quantidadeUsadaRecurso;
    }
    
    public void setQuantidadeUsadaRecurso(int quantidadeUsadaRecurso) {
        this.quantidadeUsadaRecurso = quantidadeUsadaRecurso;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


