package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaterialEventoId generated by hbm2java
 */
@Embeddable
public class MaterialEventoId  implements java.io.Serializable {


     private int idEvento;
     private int idRecurso;

    public MaterialEventoId() {
    }

    public MaterialEventoId(int idEvento, int idRecurso) {
       this.idEvento = idEvento;
       this.idRecurso = idRecurso;
    }
   


    @Column(name="id_evento", nullable=false)
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }


    @Column(name="id_recurso", nullable=false)
    public int getIdRecurso() {
        return this.idRecurso;
    }
    
    public void setIdRecurso(int idRecurso) {
        this.idRecurso = idRecurso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaterialEventoId) ) return false;
		 MaterialEventoId castOther = ( MaterialEventoId ) other; 
         
		 return (this.getIdEvento()==castOther.getIdEvento())
 && (this.getIdRecurso()==castOther.getIdRecurso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEvento();
         result = 37 * result + this.getIdRecurso();
         return result;
   }   


}


