package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name="Permissao"
    ,catalog="eventos"
)
public class Permissao  implements java.io.Serializable {


     private Integer idPermissao;
     private String designacao;

    public Permissao() {
    }

    public Permissao(String designacao) {
       this.designacao = designacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_permissao", unique=true, nullable=false)
    public Integer getIdPermissao() {
        return this.idPermissao;
    }
    
    public void setIdPermissao(Integer idPermissao) {
        this.idPermissao = idPermissao;
    }

    
    @Column(name="designacao", nullable=false, length=45)
    public String getDesignacao() {
        return this.designacao;
    }
    
    public void setDesignacao(String designacao) {
        this.designacao = designacao;
    }




}


