package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissaoPorUtilizadorId generated by hbm2java
 */
@Embeddable
public class PermissaoPorUtilizadorId  implements java.io.Serializable {


     private int idPermissao;
     private int idUtilizador;

    public PermissaoPorUtilizadorId() {
    }

    public PermissaoPorUtilizadorId(int idPermissao, int idUtilizador) {
       this.idPermissao = idPermissao;
       this.idUtilizador = idUtilizador;
    }
   


    @Column(name="id_permissao", nullable=false)
    public int getIdPermissao() {
        return this.idPermissao;
    }
    
    public void setIdPermissao(int idPermissao) {
        this.idPermissao = idPermissao;
    }


    @Column(name="id_utilizador", nullable=false)
    public int getIdUtilizador() {
        return this.idUtilizador;
    }
    
    public void setIdUtilizador(int idUtilizador) {
        this.idUtilizador = idUtilizador;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermissaoPorUtilizadorId) ) return false;
		 PermissaoPorUtilizadorId castOther = ( PermissaoPorUtilizadorId ) other; 
         
		 return (this.getIdPermissao()==castOther.getIdPermissao())
 && (this.getIdUtilizador()==castOther.getIdUtilizador());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPermissao();
         result = 37 * result + this.getIdUtilizador();
         return result;
   }   


}


