package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table(name="Servico"
    ,catalog="eventos"
)
public class Servico  implements java.io.Serializable {


     private Integer idServico;
     private String nome;
     private String email;
     private String contacto;
     private int visivel;

    public Servico() {
    }

    public Servico(String nome, String email, String contacto, int visivel) {
       this.nome = nome;
       this.email = email;
       this.contacto = contacto;
       this.visivel = visivel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_servico", unique=true, nullable=false)
    public Integer getIdServico() {
        return this.idServico;
    }
    
    public void setIdServico(Integer idServico) {
        this.idServico = idServico;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="contacto", nullable=false, length=45)
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }

    
    @Column(name="visivel", nullable=false)
    public int getVisivel() {
        return this.visivel;
    }
    
    public void setVisivel(int visivel) {
        this.visivel = visivel;
    }




}


