package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ServicoEvento generated by hbm2java
 */
@Entity
@Table(name="ServicoEvento"
    ,catalog="eventos"
)
public class ServicoEvento  implements java.io.Serializable {


     private ServicoEventoId id;
     private int estado;

    public ServicoEvento() {
    }

    public ServicoEvento(ServicoEventoId id, int estado) {
       this.id = id;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEvento", column=@Column(name="id_evento", nullable=false) ), 
        @AttributeOverride(name="idServico", column=@Column(name="id_servico", nullable=false) ) } )
    public ServicoEventoId getId() {
        return this.id;
    }
    
    public void setId(ServicoEventoId id) {
        this.id = id;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


