package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoEvento generated by hbm2java
 */
@Entity
@Table(name="TipoEvento"
    ,catalog="eventos"
)
public class TipoEvento  implements java.io.Serializable {


     private Integer idTipoEvento;
     private String designacao;

    public TipoEvento() {
    }

    public TipoEvento(String designacao) {
       this.designacao = designacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipoEvento", unique=true, nullable=false)
    public Integer getIdTipoEvento() {
        return this.idTipoEvento;
    }
    
    public void setIdTipoEvento(Integer idTipoEvento) {
        this.idTipoEvento = idTipoEvento;
    }

    
    @Column(name="designacao", nullable=false, length=45)
    public String getDesignacao() {
        return this.designacao;
    }
    
    public void setDesignacao(String designacao) {
        this.designacao = designacao;
    }




}


