package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoUtilizador generated by hbm2java
 */
@Entity
@Table(name="TipoUtilizador"
    ,catalog="eventos"
)
public class TipoUtilizador  implements java.io.Serializable {


     private Integer idTipoUtilizador;
     private String designacao;

    public TipoUtilizador() {
    }

    public TipoUtilizador(String designacao) {
       this.designacao = designacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipoUtilizador", unique=true, nullable=false)
    public Integer getIdTipoUtilizador() {
        return this.idTipoUtilizador;
    }
    
    public void setIdTipoUtilizador(Integer idTipoUtilizador) {
        this.idTipoUtilizador = idTipoUtilizador;
    }

    
    @Column(name="designacao", nullable=false, length=45)
    public String getDesignacao() {
        return this.designacao;
    }
    
    public void setDesignacao(String designacao) {
        this.designacao = designacao;
    }




}


