package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtilizadorPorEventoId generated by hbm2java
 */
@Embeddable
public class UtilizadorPorEventoId  implements java.io.Serializable {


     private int idUtilizador;
     private int idEvento;

    public UtilizadorPorEventoId() {
    }

    public UtilizadorPorEventoId(int idUtilizador, int idEvento) {
       this.idUtilizador = idUtilizador;
       this.idEvento = idEvento;
    }
   


    @Column(name="id_utilizador", nullable=false)
    public int getIdUtilizador() {
        return this.idUtilizador;
    }
    
    public void setIdUtilizador(int idUtilizador) {
        this.idUtilizador = idUtilizador;
    }


    @Column(name="id_evento", nullable=false)
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UtilizadorPorEventoId) ) return false;
		 UtilizadorPorEventoId castOther = ( UtilizadorPorEventoId ) other; 
         
		 return (this.getIdUtilizador()==castOther.getIdUtilizador())
 && (this.getIdEvento()==castOther.getIdEvento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUtilizador();
         result = 37 * result + this.getIdEvento();
         return result;
   }   


}


