package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utilizador generated by hbm2java
 */
@Entity
@Table(name="Utilizador"
    ,catalog="eventos"
)
public class Utilizador  implements java.io.Serializable {


     private Integer idUtilizador;
     private String nicename;
     private String username;
     private String password;
     private String email;
     private String nif;
     private String telemovel;
     private int idTipoUtilizador;
     private int visivel;

    public Utilizador() {
    }

    public Utilizador(String nicename, String username, String password, String email, String nif, String telemovel, int idTipoUtilizador, int visivel) {
       this.nicename = nicename;
       this.username = username;
       this.password = password;
       this.email = email;
       this.nif = nif;
       this.telemovel = telemovel;
       this.idTipoUtilizador = idTipoUtilizador;
       this.visivel = visivel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_utilizador", unique=true, nullable=false)
    public Integer getIdUtilizador() {
        return this.idUtilizador;
    }
    
    public void setIdUtilizador(Integer idUtilizador) {
        this.idUtilizador = idUtilizador;
    }

    
    @Column(name="nicename", nullable=false, length=45)
    public String getNicename() {
        return this.nicename;
    }
    
    public void setNicename(String nicename) {
        this.nicename = nicename;
    }

    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="nif", nullable=false, length=45)
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }

    
    @Column(name="telemovel", nullable=false, length=45)
    public String getTelemovel() {
        return this.telemovel;
    }
    
    public void setTelemovel(String telemovel) {
        this.telemovel = telemovel;
    }

    
    @Column(name="id_tipoUtilizador", nullable=false)
    public int getIdTipoUtilizador() {
        return this.idTipoUtilizador;
    }
    
    public void setIdTipoUtilizador(int idTipoUtilizador) {
        this.idTipoUtilizador = idTipoUtilizador;
    }

    
    @Column(name="visivel", nullable=false)
    public int getVisivel() {
        return this.visivel;
    }
    
    public void setVisivel(int visivel) {
        this.visivel = visivel;
    }




}


