package Commons;
// Generated 10/jun/2017 0:10:28 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UtilizadorPorEvento generated by hbm2java
 */
@Entity
@Table(name="UtilizadorPorEvento"
    ,catalog="eventos"
)
public class UtilizadorPorEvento  implements java.io.Serializable {


     private UtilizadorPorEventoId id;

    public UtilizadorPorEvento() {
    }

    public UtilizadorPorEvento(UtilizadorPorEventoId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idUtilizador", column=@Column(name="id_utilizador", nullable=false) ), 
        @AttributeOverride(name="idEvento", column=@Column(name="id_evento", nullable=false) ) } )
    public UtilizadorPorEventoId getId() {
        return this.id;
    }
    
    public void setId(UtilizadorPorEventoId id) {
        this.id = id;
    }




}


